---
- name: Restart systemd-resolved
  become: true
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted

- name: Restart blocky
  become: true
  ansible.builtin.systemd:
    name: blocky
    state: restarted
    daemon_reload: true
